runtime: nodejs20
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 200ms
  max_concurrent_requests: 50

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|ico))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|ico)$
    secure: always
    http_headers:
      Cache-Control: public, max-age=31536000

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
